# ----
# Site

title: DeskBoard2
baseurl:
google_analytics_key:
google_maps_javascript_api_key:
disqus_shortname:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
social:
  name: DeskBoard2

# -----
# Build

timezone: Etc/UTC

collections:

paginate: 10
paginate_path: "/blog/:num/"
permalink: pretty

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
